export function canManageClientPortfolio(tier: VendorSoluceTier | null = getActiveLicenseTier()): boolean { return tier === 'enterprise' || tier === 'assessor'; }

// Keep the rest of the file identical here...