import React from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle2, DatabaseZap, ListTodo, UploadCloud, Users } from 'lucide-react';
import { useAuth } from '../../../context/AuthContext';
import { importVendorGraphCsv } from '../../../services/vendorsoluce';
import WorkspacePageShell, { WORKSPACE_PAGE_BODY_GRID_CLASS } from '../../../components/vendorsoluce-intelligence/WorkspacePageShell';
import PanelCard from '../../../components/vendorsoluce-intelligence/PanelCard';
import { Button } from '../../../components/ui/Button';
import { resolveOrgId } from './utils';
import { isSupabaseEnabled } from '../../../lib/supabase';
import { config } from '../../../utils/config';
import { persistImportIntegrationArtifacts } from '../../../utils/vendorImportIntegration';
import { MR, WR } from 'shared/constants/routes';
const SAMPLE_PLACEHOLDER = 'Paste CSV content here…';
const VendorIntelligenceImportPage: React.FC = () => {
  const { user } = useAuth();
  const orgId = React.useMemo(() => resolveOrgId(user), [user]);
  const [vendorsCsv, setVendorsCsv] = React.useState('');
  const [servicesCsv, setServicesCsv] = React.useState('');
  const [processingCsv, setProcessingCsv] = React.useState('');
  const [edgesCsv, setEdgesCsv] = React.useState('');
  const [status, setStatus] = React.useState<string | null>(null);
  const [busy, setBusy] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const graphImportLive = isSupabaseEnabled() && !config.app.demoMode;
  const canImport = Boolean(
    graphImportLive && orgId && vendorsCsv.trim() && servicesCsv.trim() && processingCsv.trim() && edgesCsv.trim(),
  );
  const handleImport = async () => {
    if (!orgId) {
      setError('No organization id is available for this session.');
      return;
    }
    if (!graphImportLive) {
      setError('Graph import requires a connected database. Demo mode uses precomputed portfolio metrics instead.');
      return;
    }
    setBusy(true);
    setError(null);
    setStatus(null);
    try {
      const result = await importVendorGraphCsv(orgId, { vendorsCsv, servicesCsv, processingCsv, edgesCsv });
      persistImportIntegrationArtifacts(vendorsCsv, result);
      setStatus(
        `Imported ${result.insertedNodes} nodes and ${result.insertedEdges} edges, then recomputed metrics. Onboarding and roadmap were updated with review backlog items.`,
      );
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Import failed');
    } finally {
      setBusy(false);
    }
  };
  return (
    <WorkspacePageShell
      title="Dependency graph import"
      description="Import dependency CSVs and recompute graph metrics."
      actions={[{ label: busy ? 'Importing…' : 'Run import', onClick: handleImport, variant: 'primary' }]}
      stats={[
        { label: 'Input set', value: '4 CSV files', hint: 'Required for graph build' },
        { label: 'Recompute', value: 'Automatic', hint: 'Metrics rerun after import' },
      ]}
    >
      {!graphImportLive ? (
        <div className="rounded-xl border border-blue-200 bg-blue-50/80 px-4 py-3 text-sm text-blue-900 dark:border-blue-900/60 dark:bg-blue-950/30 dark:text-blue-200">
          Demo / offline: CSV import is disabled. Use the vendor intelligence portfolio for sample dependency metrics, or connect
          Supabase and disable demo mode for full imports.
        </div>
      ) : null}
      {error ? (
        <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900/70 dark:bg-red-950/30 dark:text-red-300">
          {error}
        </div>
      ) : null}
      {status ? (
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:border-emerald-900/70 dark:bg-emerald-950/30 dark:text-emerald-300">
          {status}
        </div>
      ) : null}
      <div className={`${WORKSPACE_PAGE_BODY_GRID_CLASS} xl:grid-cols-[1.4fr,1fr]`}>
        <div className="grid gap-6">
          {(
            [
              ['vendors.csv', vendorsCsv, setVendorsCsv],
              ['services.csv', servicesCsv, setServicesCsv],
              ['processing.csv', processingCsv, setProcessingCsv],
              ['edges.csv', edgesCsv, setEdgesCsv],
            ] as const
          ).map(([label, value, setter]) => (
            <PanelCard key={label} title={label} description="Paste the raw CSV file content exactly as generated by your source bundle.">
              <textarea
                value={value}
                onChange={(e) => setter(e.target.value)}
                placeholder={SAMPLE_PLACEHOLDER}
                disabled={!graphImportLive}
                className="min-h-[180px] w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm text-gray-900 outline-none ring-0 transition placeholder:text-gray-400 focus:border-emerald-500 disabled:cursor-not-allowed disabled:opacity-60 dark:border-gray-800 dark:bg-gray-950 dark:text-white"
              />
            </PanelCard>
          ))}
        </div>
        <div className="grid gap-6">
          <PanelCard title="Import requirements" description="The graph engine expects a coherent four-file set so the node and edge identities line up.">
            <div className="space-y-4 text-sm text-gray-600 dark:text-gray-300">
              <div className="flex items-start gap-3">
                <UploadCloud className="mt-0.5 h-4 w-4 text-emerald-600" />
                <span>Use the same org id across imports. Mixed tenant ids will fragment the graph.</span>
              </div>
              <div className="flex items-start gap-3">
                <DatabaseZap className="mt-0.5 h-4 w-4 text-emerald-600" />
                <span>The import pipeline upserts graph nodes, replaces graph edges, then recomputes vendor metrics.</span>
              </div>
              <div className="flex items-start gap-3">
                <CheckCircle2 className="mt-0.5 h-4 w-4 text-emerald-600" />
                <span>After import, review portfolio coverage and vendor linkage before relying on scenario outputs.</span>
              </div>
            </div>
          </PanelCard>
          <PanelCard title="Execution" description="Run the import only when all four CSV datasets are present and scoped to the same portfolio snapshot.">
            <Button variant="primary" onClick={handleImport} disabled={!canImport || busy} className="w-full justify-center">
              {busy ? 'Importing dependency graph…' : 'Import and recompute'}
            </Button>
            {!orgId ? (
              <div className="mt-3 text-sm text-amber-700 dark:text-amber-300">No organization id is available in the current auth context.</div>
            ) : null}
          </PanelCard>
          <PanelCard
            title="After import"
            description="We prefill vendor onboarding from vendors.csv where possible and add dated milestones for VIRA, requirements, evidence, and assessments."
          >
            <ul className="space-y-3 text-sm text-gray-600 dark:text-gray-300">
              <li className="flex gap-2">
                <Users className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600 dark:text-emerald-400" aria-hidden />
                <span>
                  <Link to={MR.VENDOR_ONBOARDING} className="font-medium text-vendorsoluce-green hover:underline dark:text-vendorsoluce-light-green">
                    Vendor onboarding
                  </Link>{' '}
                  picks up the primary vendor row from your last successful import.
                </span>
              </li>
              <li className="flex gap-2">
                <ListTodo className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600 dark:text-emerald-400" aria-hidden />
                <span>
                  <Link to={WR.COMPLIANCE_ROADMAP} className="font-medium text-vendorsoluce-green hover:underline dark:text-vendorsoluce-light-green">
                    Roadmap & calendar
                  </Link>{' '}
                  receives a review backlog (VIRA reports, security definitions, evidence, assessments) with target dates.
                </span>
              </li>
            </ul>
          </PanelCard>
        </div>
      </div>
    </WorkspacePageShell>
  );
};
export default VendorIntelligenceImportPage;
