import type { GraphNode } from '../contracts/graph';
import type { VendorCentralityMetrics } from '../contracts/metrics';
import type { ScenarioRunOutput } from '../contracts/scenarios';

export function renderVendorCascadeHtml(input: {
  vendor: GraphNode;
  metrics: VendorCentralityMetrics;
  explanation: string;
  scenario?: ScenarioRunOutput;
}): string {
  const { vendor, metrics, explanation, scenario } = input;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>${vendor.name} | Vendor Cascade Brief</title>
<style>
body{font-family:Arial,sans-serif;line-height:1.45;margin:32px;color:#111}
h1,h2{margin:0 0 12px}
.section{margin-top:24px}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}
.card{border:1px solid #ddd;border-radius:8px;padding:12px}
.small{color:#555;font-size:12px}
</style>
</head>
<body>
<h1>${vendor.name} — Vendor Cascade Brief</h1>
<p class="small">Generated by VendorSoluce dependency intelligence</p>

<div class="section">
  <div class="grid">
    <div class="card"><strong>SDS</strong><div>${metrics.systemicDependencyScore.toFixed(2)}</div></div>
    <div class="card"><strong>PRS</strong><div>${metrics.propagationRiskScore.toFixed(2)}</div></div>
    <div class="card"><strong>HCS</strong><div>${metrics.hiddenConcentrationScore.toFixed(2)}</div></div>
  </div>
</div>

<div class="section">
  <h2>Interpretation</h2>
  <p>${explanation}</p>
</div>

<div class="section">
  <h2>Blast Radius</h2>
  <ul>
    <li>Services impacted: ${metrics.blastRadiusServiceCount}</li>
    <li>Processing activities impacted: ${metrics.blastRadiusProcessingCount}</li>
    <li>Jurisdictions impacted: ${metrics.blastRadiusJurisdictionCount}</li>
    <li>Weighted impact: ${metrics.blastRadiusWeightedImpact.toFixed(2)}</li>
  </ul>
</div>

${scenario ? `<div class="section">
  <h2>Scenario Summary</h2>
  <p>${scenario.narrative.summary}</p>
  <ul>${scenario.narrative.drivers.map(d => `<li>${d}</li>`).join('')}</ul>
</div>` : ''}

</body>
</html>`;
}
