import { loadDocxParser, loadPdfRenderer } from '../../../shared/src/utils/lazyModules';
import { downloadFromStorage, fileExists } from './supabaseStorage';
import { pdf, pdfPriorityColor, pdfScoreColor } from './pdfHtmlPalette';

const MAX_UPLOAD_FILE_SIZE = 20 * 1024 * 1024; // 20 MB

// Storage bucket for templates
const TEMPLATES_BUCKET = 'templates';

/**
 * Generate PDF from HTML content
 */
export const generatePdfFromHtml = async (htmlContent: string, filename: string) => {
  try {
    const { renderHtmlToPdf } = await loadPdfRenderer();
    const pdfDoc = await renderHtmlToPdf(htmlContent);
    pdfDoc.save(filename);
  } catch (error) {
    console.error('PDF generation failed:', error);
    throw new Error(`Failed to generate PDF: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};

export const generateResultsPdf = async (
  title: string,
  overallScore: number,
  sectionScores: { title: string; percentage: number }[],
  completedDate: string,
  filename: string
) => {
  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid ${pdf.navy}; padding-bottom: 20px;">
        <h1 style="color: ${pdf.navy}; margin: 0; font-size: 28px;">${title}</h1>
        <p style="color: ${pdf.mutedText}; margin: 10px 0 0 0; font-size: 16px;">Completed: ${completedDate}</p>
      </div>
      
      <div style="text-align: center; margin-bottom: 40px; padding: 30px; background-color: ${pdf.slate50}; border-radius: 8px; border: 1px solid ${pdf.slate200};">
        <div style="font-size: 48px; font-weight: bold; color: ${pdfScoreColor(overallScore)}; margin-bottom: 10px;">${overallScore}%</div>
        <div style="font-size: 18px; color: ${pdf.gray700};">Overall Compliance Score</div>
      </div>
      
      <h2 style="color: ${pdf.teal}; margin-bottom: 20px; font-size: 22px;">Section Scores</h2>
      <div style="margin-bottom: 30px;">
        ${sectionScores.map(section => `
          <div style="margin-bottom: 15px; padding: 15px; background-color: ${pdf.gray50}; border-radius: 6px; border-left: 4px solid ${pdfScoreColor(section.percentage)};">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
              <span style="font-weight: 600; color: ${pdf.gray700};">${section.title}</span>
              <span style="font-weight: 600; color: ${pdfScoreColor(section.percentage)};">${section.percentage}%</span>
            </div>
            <div style="width: 100%; height: 8px; background-color: ${pdf.gray200}; border-radius: 4px; overflow: hidden;">
              <div style="width: ${section.percentage}%; height: 100%; background-color: ${pdfScoreColor(section.percentage)}; border-radius: 4px;"></div>
            </div>
          </div>
        `).join('')}
      </div>
      
      <div style="margin-top: 40px; padding: 20px; background-color: ${pdf.blue50}; border-radius: 8px; border: 1px solid ${pdf.blue};">
        <h3 style="color: ${pdf.navy}; margin: 0 0 10px 0; font-size: 18px;">Assessment Summary</h3>
        <p style="color: ${pdf.gray700}; margin: 0; line-height: 1.6;">
          This assessment evaluates your organization's supply chain risk management practices based on NIST SP 800-161 guidelines. 
          Scores above 80% indicate strong compliance, while scores below 60% suggest areas requiring immediate attention.
        </p>
      </div>
      
      <div style="margin-top: 30px; text-align: center; color: ${pdf.neutralGray}; font-size: 12px; border-top: 1px solid ${pdf.gray200}; padding-top: 20px;">
        <p style="margin: 0;">Generated by VendorSoluce Supply Chain Risk Management Platform</p>
        <p style="margin: 5px 0 0 0;">© ${new Date().getFullYear()} VendorSoluce. All rights reserved.</p>
      </div>
    </div>
  `;

  await generatePdfFromHtml(htmlContent, filename);
};

/**
 * Generate Premium PDF Report with enhanced features
 * Includes: Executive summary, detailed analytics, charts, recommendations
 */
export const generatePremiumReportPdf = async (
  title: string,
  overallScore: number,
  sectionScores: { title: string; percentage: number }[],
  completedDate: string,
  filename: string,
  additionalData?: {
    recommendations?: any[];
    riskTrends?: { month: string; score: number }[];
    vendorCount?: number;
    criticalFindings?: string[];
  }
) => {
  const getScoreGrade = (score: number) => {
    if (score >= 90) return 'A';
    if (score >= 80) return 'B';
    if (score >= 70) return 'C';
    if (score >= 60) return 'D';
    return 'F';
  };

  const htmlContent = `
    <div style="font-family: 'Arial', 'Helvetica', sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: linear-gradient(to bottom, ${pdf.slate50} 0%, ${pdf.white} 100%);">
      <!-- Premium Header with Logo -->
      <div style="text-align: center; margin-bottom: 40px; padding: 30px; background: linear-gradient(135deg, ${pdf.navy} 0%, ${pdf.teal} 100%); color: white; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <div style="font-size: 32px; font-weight: bold; margin-bottom: 10px;">PREMIUM REPORT</div>
        <h1 style="color: white; margin: 0; font-size: 28px; font-weight: 300;">${title}</h1>
        <p style="color: rgba(255,255,255,0.9); margin: 15px 0 0 0; font-size: 14px;">Completed: ${completedDate}</p>
      </div>
      
      <!-- Executive Summary Card -->
      <div style="background: white; padding: 30px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 30px; border-left: 5px solid ${pdfScoreColor(overallScore)};">
        <h2 style="color: ${pdf.navy}; margin: 0 0 20px 0; font-size: 22px; font-weight: 600;">Executive Summary</h2>
        <div style="display: flex; align-items: center; gap: 30px; margin-bottom: 20px;">
          <div style="text-align: center; flex: 1;">
            <div style="font-size: 64px; font-weight: bold; color: ${pdfScoreColor(overallScore)}; margin-bottom: 5px;">${overallScore}%</div>
            <div style="font-size: 24px; color: ${pdfScoreColor(overallScore)}; font-weight: 600; margin-bottom: 5px;">Grade ${getScoreGrade(overallScore)}</div>
            <div style="font-size: 14px; color: ${pdf.neutralGray};">Overall Compliance Score</div>
          </div>
          <div style="flex: 1; padding-left: 20px; border-left: 2px solid ${pdf.gray200};">
            <p style="color: ${pdf.gray700}; line-height: 1.8; margin: 0; font-size: 14px;">
              ${overallScore >= 80 
                ? 'Your organization demonstrates strong supply chain risk management practices aligned with NIST SP 800-161 guidelines. Continue monitoring and improvement efforts to maintain compliance.'
                : overallScore >= 60
                ? 'Your organization shows moderate compliance with NIST SP 800-161. Focus on addressing high-priority recommendations to strengthen your security posture.'
                : 'Your organization requires immediate attention to improve supply chain risk management. Prioritize critical recommendations to achieve compliance.'}
            </p>
          </div>
        </div>
        ${additionalData?.vendorCount ? `
          <div style="margin-top: 20px; padding: 15px; background: ${pdf.blue50}; border-radius: 8px;">
            <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; text-align: center;">
              <div>
                <div style="font-size: 24px; font-weight: bold; color: ${pdf.navy};">${additionalData.vendorCount}</div>
                <div style="font-size: 12px; color: ${pdf.neutralGray};">Vendors Assessed</div>
              </div>
              <div>
                <div style="font-size: 24px; font-weight: bold; color: ${pdf.navy};">${sectionScores.length}</div>
                <div style="font-size: 12px; color: ${pdf.neutralGray};">Assessment Domains</div>
              </div>
              <div>
                <div style="font-size: 24px; font-weight: bold; color: ${pdf.navy};">${additionalData.criticalFindings?.length || 0}</div>
                <div style="font-size: 12px; color: ${pdf.neutralGray};">Critical Findings</div>
              </div>
            </div>
          </div>
        ` : ''}
      </div>
      
      <!-- Detailed Section Scores -->
      <div style="background: white; padding: 30px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 30px;">
        <h2 style="color: ${pdf.teal}; margin: 0 0 25px 0; font-size: 22px; font-weight: 600;">Detailed Section Analysis</h2>
        ${sectionScores.map(section => `
          <div style="margin-bottom: 20px; padding: 20px; background: ${pdf.gray50}; border-radius: 8px; border-left: 4px solid ${pdfScoreColor(section.percentage)};">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px;">
              <span style="font-weight: 600; color: ${pdf.gray700}; font-size: 16px;">${section.title}</span>
              <div style="text-align: right;">
                <span style="font-weight: 700; color: ${pdfScoreColor(section.percentage)}; font-size: 20px;">${section.percentage}%</span>
                <div style="font-size: 11px; color: ${pdf.neutralGray}; margin-top: 2px;">Grade ${getScoreGrade(section.percentage)}</div>
              </div>
            </div>
            <div style="width: 100%; height: 12px; background-color: ${pdf.gray200}; border-radius: 6px; overflow: hidden; margin-bottom: 10px;">
              <div style="width: ${section.percentage}%; height: 100%; background: linear-gradient(90deg, ${pdfScoreColor(section.percentage)} 0%, ${pdfScoreColor(section.percentage)}CC 100%); border-radius: 6px;"></div>
            </div>
            <p style="color: ${pdf.neutralGray}; margin: 0; font-size: 13px; line-height: 1.6;">
              ${section.percentage >= 80 
                ? 'This section demonstrates strong compliance with recommended practices.'
                : section.percentage >= 60
                ? 'This section shows moderate compliance. Review recommendations for improvement opportunities.'
                : 'This section requires immediate attention. Prioritize implementing recommended controls.'}
            </p>
          </div>
        `).join('')}
      </div>
      
      ${additionalData?.recommendations && additionalData.recommendations.length > 0 ? `
        <!-- Priority Recommendations -->
        <div style="background: white; padding: 30px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 30px;">
          <h2 style="color: ${pdf.teal}; margin: 0 0 25px 0; font-size: 22px; font-weight: 600;">Priority Recommendations</h2>
          ${additionalData.recommendations.slice(0, 5).map((rec: any) => `
            <div style="margin-bottom: 15px; padding: 15px; background: ${pdf.amber100}; border-radius: 8px; border-left: 4px solid ${pdf.riskMedium};">
              <div style="font-weight: 600; color: ${pdf.gray700}; margin-bottom: 5px;">${rec.title || rec.category}</div>
              <p style="color: ${pdf.neutralGray}; margin: 0; font-size: 13px; line-height: 1.5;">${rec.description || rec.recommendation}</p>
            </div>
          `).join('')}
        </div>
      ` : ''}
      
      ${additionalData?.criticalFindings && additionalData.criticalFindings.length > 0 ? `
        <!-- Critical Findings -->
        <div style="background: ${pdf.red50}; padding: 30px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 30px; border-left: 5px solid ${pdf.riskCritical};">
          <h2 style="color: ${pdf.riskCritical}; margin: 0 0 20px 0; font-size: 22px; font-weight: 600;">⚠️ Critical Findings</h2>
          <ul style="margin: 0; padding-left: 20px; color: ${pdf.gray700}; line-height: 1.8;">
            ${additionalData.criticalFindings.map((finding: string) => `<li style="margin-bottom: 8px;">${finding}</li>`).join('')}
          </ul>
        </div>
      ` : ''}
      
      <!-- Next Steps -->
      <div style="background: linear-gradient(135deg, ${pdf.blue50} 0%, ${pdf.sky100} 100%); padding: 30px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 30px;">
        <h2 style="color: ${pdf.navy}; margin: 0 0 15px 0; font-size: 22px; font-weight: 600;">Recommended Next Steps</h2>
        <ol style="margin: 0; padding-left: 20px; color: ${pdf.gray700}; line-height: 2;">
          <li>Review and prioritize recommendations based on business impact</li>
          <li>Assign ownership and establish timelines for implementation</li>
          <li>Schedule quarterly reassessments to track progress</li>
          <li>Document remediation efforts for compliance records</li>
          <li>Engage with VendorSoluce support for implementation guidance</li>
        </ol>
      </div>
      
      <!-- Premium Footer -->
      <div style="margin-top: 40px; text-align: center; color: ${pdf.neutralGray}; font-size: 11px; border-top: 2px solid ${pdf.gray200}; padding-top: 20px;">
        <div style="font-weight: 600; color: ${pdf.navy}; margin-bottom: 5px;">PREMIUM REPORT</div>
        <p style="margin: 5px 0;">Generated by VendorSoluce Supply Chain Risk Management Platform</p>
        <p style="margin: 5px 0;">© ${new Date().getFullYear()} VendorSoluce. All rights reserved.</p>
        <p style="margin: 10px 0 0 0; font-size: 10px; color: ${pdf.gray400};">This premium report includes enhanced analytics, executive summaries, and detailed recommendations.</p>
      </div>
    </div>
  `;

  await generatePdfFromHtml(htmlContent, filename);
};

export const generateRecommendationsPdf = async (
  title: string,
  recommendations: any[],
  date: string,
  filename: string
) => {
  const getPriorityIcon = (priority: string) => {
    switch (priority) {
      case 'critical': return '🔴';
      case 'high': return '🟠';
      case 'medium': return '🟡';
      case 'low': return '🟢';
      default: return '⚪';
    }
  };

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid ${pdf.navy}; padding-bottom: 20px;">
        <h1 style="color: ${pdf.navy}; margin: 0; font-size: 28px;">${title}</h1>
        <p style="color: ${pdf.mutedText}; margin: 10px 0 0 0; font-size: 16px;">Generated: ${date}</p>
      </div>
      
      <div style="margin-bottom: 30px; padding: 20px; background-color: ${pdf.blue50}; border-radius: 8px; border: 1px solid ${pdf.blue};">
        <h2 style="color: ${pdf.navy}; margin: 0 0 10px 0; font-size: 20px;">Executive Summary</h2>
        <p style="color: ${pdf.gray700}; margin: 0; line-height: 1.6;">
          This document contains ${recommendations.length} prioritized recommendations to improve your supply chain security posture. 
          Recommendations are based on NIST SP 800-161 guidelines and your assessment results.
        </p>
      </div>
      
      <h2 style="color: ${pdf.teal}; margin-bottom: 20px; font-size: 22px;">Recommendations by Priority</h2>
      
      ${recommendations.map((rec) => `
        <div style="margin-bottom: 25px; padding: 20px; background-color: ${pdf.gray50}; border-radius: 8px; border-left: 4px solid ${pdfPriorityColor(rec.priority)};">
          <div style="display: flex; align-items: center; margin-bottom: 15px;">
            <span style="font-size: 18px; margin-right: 8px;">${getPriorityIcon(rec.priority)}</span>
            <h3 style="color: ${pdf.gray700}; margin: 0; font-size: 18px; font-weight: 600;">${rec.title}</h3>
            <span style="background-color: ${pdfPriorityColor(rec.priority)}; color: white; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; margin-left: auto;">
              ${rec.priority.toUpperCase()}
            </span>
          </div>
          
          <p style="color: ${pdf.neutralGray}; margin: 0 0 15px 0; line-height: 1.6;">${rec.description}</p>
          
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px; font-size: 14px;">
            <div>
              <strong style="color: ${pdf.gray700};">Category:</strong> <span style="color: ${pdf.neutralGray};">${rec.category}</span>
            </div>
            <div>
              <strong style="color: ${pdf.gray700};">Effort:</strong> <span style="color: ${pdf.neutralGray};">${rec.effort}</span>
            </div>
            <div>
              <strong style="color: ${pdf.gray700};">Timeframe:</strong> <span style="color: ${pdf.neutralGray};">${rec.timeframe}</span>
            </div>
            <div>
              <strong style="color: ${pdf.gray700};">Impact:</strong> <span style="color: ${pdf.neutralGray};">High</span>
            </div>
          </div>
          
          ${rec.steps && rec.steps.length > 0 ? `
            <div style="margin-top: 15px;">
              <strong style="color: ${pdf.gray700}; font-size: 14px;">Implementation Steps:</strong>
              <ol style="margin: 8px 0 0 20px; padding: 0; color: ${pdf.neutralGray}; font-size: 13px; line-height: 1.5;">
                ${rec.steps.slice(0, 3).map((step: string) => `<li style="margin-bottom: 4px;">${step}</li>`).join('')}
                ${rec.steps.length > 3 ? `<li style="color: ${pdf.gray400}; font-style: italic;">... and ${rec.steps.length - 3} more steps</li>` : ''}
              </ol>
            </div>
          ` : ''}
        </div>
      `).join('')}
      
      <div style="margin-top: 40px; padding: 20px; background-color: ${pdf.amber100}; border-radius: 8px; border: 1px solid ${pdf.riskMedium};">
        <h3 style="color: ${pdf.amber800}; margin: 0 0 10px 0; font-size: 18px;">⚠️ Implementation Guidelines</h3>
        <ul style="color: ${pdf.amber900}; margin: 0; padding-left: 20px; line-height: 1.6;">
          <li>Address critical and high-priority recommendations first</li>
          <li>Assign clear ownership and timelines for each recommendation</li>
          <li>Track implementation progress regularly</li>
          <li>Re-assess your supply chain security posture quarterly</li>
        </ul>
      </div>
      
      <div style="margin-top: 30px; text-align: center; color: ${pdf.neutralGray}; font-size: 12px; border-top: 1px solid ${pdf.gray200}; padding-top: 20px;">
        <p style="margin: 0;">Generated by VendorSoluce Supply Chain Risk Management Platform</p>
        <p style="margin: 5px 0 0 0;">© ${new Date().getFullYear()} VendorSoluce. All rights reserved.</p>
      </div>
    </div>
  `;

  await generatePdfFromHtml(htmlContent, filename);
};

// Enhanced template download function with real file generation
export const downloadTemplateFile = async (templatePath: string, filename: string) => {
  let content = '';
  let mimeType = 'text/plain';
  
  try {
    // Convert local path to storage path
    const storagePath = templatePath.startsWith('/templates/') 
      ? templatePath.substring('/templates/'.length)
      : templatePath.startsWith('templates/')
      ? templatePath.substring('templates/'.length)
      : templatePath;
    
    // Check if file exists in Supabase Storage
    const exists = await fileExists(TEMPLATES_BUCKET, storagePath);
    
    if (exists) {
      // Download from Supabase Storage
      const blob = await downloadFromStorage(TEMPLATES_BUCKET, storagePath);
      content = await blob.text();
      mimeType = blob.type || 'text/plain';
    } else {
      // Fallback: try to fetch from public folder (for development)
      const response = await fetch(templatePath);
      if (response.ok) {
        content = await response.text();
        mimeType = response.headers.get('content-type') || 'text/plain';
      } else {
        throw new Error('Template not found in storage or public folder');
      }
    }
    
    if (filename.endsWith('.html') || filename.endsWith('.docx')) {
      mimeType = 'text/html';
    } else if (filename.endsWith('.json')) {
      mimeType = 'application/json';
    } else if (filename.endsWith('.csv') || filename.endsWith('.xlsx')) {
      mimeType = 'text/csv';
    } else if (filename.endsWith('.sh')) {
      mimeType = 'text/plain';
    } else if (filename.endsWith('.pdf')) {
      // Generate PDF from HTML template
      const htmlStoragePath = storagePath.replace('.pdf', '.html');
      const htmlExists = await fileExists(TEMPLATES_BUCKET, htmlStoragePath);
      
      if (htmlExists) {
        const htmlBlob = await downloadFromStorage(TEMPLATES_BUCKET, htmlStoragePath);
        const htmlContent = await htmlBlob.text();
        await generatePdfFromHtml(htmlContent, filename);
        return;
      } else {
        // Fallback: try to fetch HTML from public folder
        const htmlTemplatePath = templatePath.replace('.pdf', '.html');
        try {
          const response = await fetch(htmlTemplatePath);
          if (response.ok) {
            const htmlContent = await response.text();
            await generatePdfFromHtml(htmlContent, filename);
            return;
          } else {
            // Generate mock PDF content if HTML template not found
            const mockHtmlContent = generateMockHtmlContent(filename);
            await generatePdfFromHtml(mockHtmlContent, filename);
            return;
          }
        } catch (fetchError) {
          // Generate mock PDF content if HTML template not found
          const mockHtmlContent = generateMockHtmlContent(filename);
          await generatePdfFromHtml(mockHtmlContent, filename);
          return;
        }
      }
    }

    // Create blob and trigger download
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Error downloading template:', error);
    // Fallback to mock content if template file doesn't exist in storage or public folder
    generateMockTemplate(filename);
  }
};

const generateMockTemplate = (filename: string) => {
  let content = '';
  let mimeType = 'text/plain';
  
  if (filename.endsWith('.html') || filename.endsWith('.docx')) {
    content = `
      <html>
        <head>
          <title>VendorSoluce Template - ${filename}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: ${pdf.navy}; }
            .content { border: 1px solid ${pdf.borderLight}; padding: 20px; margin: 20px 0; }
          </style>
        </head>
        <body>
          <h1>VendorSoluce Template</h1>
          <p>This is a demonstration template file for: ${filename}</p>
          <div class="content">
            <h2>Template Content Would Appear Here</h2>
            <p>In a production environment, this would be a fully-formatted template.</p>
          </div>
        </body>
      </html>
    `;
    mimeType = 'text/html';
  } else if (filename.endsWith('.json')) {
    content = JSON.stringify({
      template: filename,
      description: "VendorSoluce template file",
      generatedAt: new Date().toISOString(),
      note: "This is a demonstration template file"
    }, null, 2);
    mimeType = 'application/json';
  } else if (filename.endsWith('.csv') || filename.endsWith('.xlsx')) {
    content = `"Template","Description","Generated At"
"${filename}","VendorSoluce template file","${new Date().toISOString()}"`;
    mimeType = 'text/csv';
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
const escapeHtml = (str: string): string =>
  str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const generateMockHtmlContent = (filename: string): string => {
  const safeFilename = escapeHtml(filename);
  return `
    <html>
      <head>
        <title>VendorSoluce Template - ${safeFilename}</title>
        <style>
          body { 
            font-family: Arial, sans-serif; 
            padding: 40px; 
            line-height: 1.6; 
            color: ${pdf.bodyText};
          }
          h1 { 
            color: ${pdf.navy}; 
            border-bottom: 2px solid ${pdf.navy};
            padding-bottom: 10px;
            margin-bottom: 30px;
          }
          .header {
            text-align: center;
            margin-bottom: 40px;
          }
          .content { 
            border: 1px solid ${pdf.borderLight}; 
            padding: 30px; 
            margin: 20px 0; 
            background-color: ${pdf.tableHeaderBg};
            border-radius: 8px;
          }
          .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: ${pdf.mutedText};
            border-top: 1px solid ${pdf.borderLight};
            padding-top: 20px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>VendorSoluce Template</h1>
          <p>Template File: ${safeFilename}</p>
        </div>
        <div class="content">
          <h2>Template Content</h2>
          <p>This is a demonstration template file generated by VendorSoluce.</p>
          <p>In a production environment, this would contain the actual template content for: <strong>${escapeHtml(filename.replace('.pdf', ''))}</strong></p>
          <p>The template would include relevant forms, guidelines, and documentation specific to supply chain risk management and NIST SP 800-161 compliance.</p>
        </div>
        <div class="footer">
          <p>Generated by VendorSoluce Supply Chain Risk Management Platform</p>
          <p>© ${new Date().getFullYear()} VendorSoluce. All rights reserved.</p>
        </div>
      </body>
    </html>
  `;
};

/**
 * Extract text content from Word document (DOCX)
 */
export const extractWordDocumentContent = async (file: File | Blob): Promise<string> => {
  if (file.size > MAX_UPLOAD_FILE_SIZE) {
    throw new Error(`File too large. Maximum allowed size is ${MAX_UPLOAD_FILE_SIZE / 1024 / 1024}MB.`);
  }
  try {
    const { extractDocxRawText } = await loadDocxParser();
    return await extractDocxRawText(file);
  } catch (error) {
    console.error('Error extracting Word document content:', error);
    throw new Error(`Failed to extract Word document content: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};

/**
 * Extract HTML content from Word document (DOCX)
 */
export const extractWordDocumentHtml = async (file: File | Blob): Promise<string> => {
  if (file.size > MAX_UPLOAD_FILE_SIZE) {
    throw new Error(`File too large. Maximum allowed size is ${MAX_UPLOAD_FILE_SIZE / 1024 / 1024}MB.`);
  }
  try {
    const { extractDocxHtml } = await loadDocxParser();
    return await extractDocxHtml(file);
  } catch (error) {
    console.error('Error extracting Word document HTML:', error);
    throw new Error(`Failed to extract Word document HTML: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};

/**
 * Interface for detailed assessment question data
 */
export interface AssessmentQuestion {
  id: string;
  section: string;
  question: string;
  answer: string | number | boolean | null;
  type: 'yes_no' | 'yes_no_na' | 'text' | 'file_upload' | 'scale';
  guidance?: string;
  evidenceFiles?: string[];
}

/**
 * Interface for comprehensive assessment report data
 */
export interface ComprehensiveAssessmentData {
  assessmentName: string;
  frameworkName: string;
  overallScore: number;
  sectionScores: { title: string; percentage: number; completed: boolean }[];
  completedDate: string;
  assessmentId?: string;
  vendorName?: string;
  organizationName?: string;
  questions?: AssessmentQuestion[];
  wordDocuments?: Array<{ name: string; content: string }>;
  metadata?: {
    contactEmail?: string;
    dueDate?: string;
    status?: string;
  };
}

/**
 * Generate comprehensive assessment report PDF with detailed results and Word document content
 */
export const generateComprehensiveAssessmentPdf = async (
  data: ComprehensiveAssessmentData,
  filename: string
) => {
  const getScoreLabel = (score: number) => {
    if (score >= 80) return 'Low Risk';
    if (score >= 60) return 'Moderate Risk';
    if (score >= 40) return 'High Risk';
    return 'Critical Risk';
  };

  const formatAnswer = (answer: string | number | boolean | null, type: string): string => {
    if (answer === null || answer === undefined) return 'Not answered';
    if (type === 'yes_no' || type === 'yes_no_na') {
      if (answer === true || answer === 'yes' || answer === 'Yes') return 'Yes';
      if (answer === false || answer === 'no' || answer === 'No') return 'No';
      if (answer === 'na' || answer === 'N/A') return 'N/A';
      return String(answer);
    }
    return String(answer);
  };

  // Build questions HTML if available
  const questionsHtml = data.questions && data.questions.length > 0 ? `
    <div style="margin-top: 40px; page-break-before: always;">
      <h2 style="color: ${pdf.teal}; margin-bottom: 20px; font-size: 22px; border-bottom: 2px solid ${pdf.teal}; padding-bottom: 10px;">
        Detailed Assessment Responses
      </h2>
      ${data.questions.reduce((acc, question, index) => {
        const currentSection = question.section;
        const prevSection = index > 0 ? data.questions![index - 1].section : null;
        const sectionHeader = currentSection !== prevSection ? `
          <div style="margin-top: ${index > 0 ? '30px' : '0'}; margin-bottom: 15px;">
            <h3 style="color: ${pdf.navy}; font-size: 18px; font-weight: 600; background-color: ${pdf.blue50}; padding: 10px 15px; border-radius: 6px; border-left: 4px solid ${pdf.navy};">
              ${currentSection}
            </h3>
          </div>
        ` : '';
        
        return acc + sectionHeader + `
          <div style="margin-bottom: 20px; padding: 15px; background-color: ${pdf.gray50}; border-radius: 6px; border-left: 3px solid ${pdf.blue};">
            <div style="display: flex; justify-content: space-between; align-items: start; margin-bottom: 10px;">
              <div style="flex: 1;">
                <div style="font-weight: 600; color: ${pdf.gray700}; margin-bottom: 5px; font-size: 14px;">
                  ${question.id}: ${question.question}
                </div>
                ${question.guidance ? `
                  <div style="font-size: 12px; color: ${pdf.neutralGray}; font-style: italic; margin-top: 5px;">
                    Guidance: ${question.guidance}
                  </div>
                ` : ''}
              </div>
            </div>
            <div style="margin-top: 10px;">
              <div style="display: flex; align-items: center; gap: 10px;">
                <strong style="color: ${pdf.gray700}; font-size: 13px;">Response:</strong>
                <span style="background-color: ${pdfScoreColor(typeof question.answer === 'number' ? question.answer : 0)}; color: white; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600;">
                  ${formatAnswer(question.answer, question.type)}
                </span>
              </div>
              ${question.evidenceFiles && question.evidenceFiles.length > 0 ? `
                <div style="margin-top: 8px; font-size: 12px; color: ${pdf.neutralGray};">
                  <strong>Evidence Files:</strong> ${question.evidenceFiles.join(', ')}
                </div>
              ` : ''}
            </div>
          </div>
        `;
      }, '')}
    </div>
  ` : '';

  // Build Word documents content HTML if available
  const wordDocumentsHtml = data.wordDocuments && data.wordDocuments.length > 0 ? `
    <div style="margin-top: 40px; page-break-before: always;">
      <h2 style="color: ${pdf.teal}; margin-bottom: 20px; font-size: 22px; border-bottom: 2px solid ${pdf.teal}; padding-bottom: 10px;">
        Supporting Documentation
      </h2>
      ${data.wordDocuments.map((doc, index) => `
        <div style="margin-bottom: 30px; padding: 20px; background-color: ${pdf.gray50}; border-radius: 8px; border: 1px solid ${pdf.gray200};">
          <h3 style="color: ${pdf.navy}; margin: 0 0 15px 0; font-size: 16px; font-weight: 600;">
            Document ${index + 1}: ${doc.name}
          </h3>
          <div style="background-color: white; padding: 15px; border-radius: 6px; border: 1px solid ${pdf.gray200}; max-height: 400px; overflow-y: auto; font-size: 12px; line-height: 1.6; color: ${pdf.gray700}; white-space: pre-wrap;">
            ${doc.content.substring(0, 5000)}${doc.content.length > 5000 ? '\n\n[... Content truncated for brevity ...]' : ''}
          </div>
        </div>
      `).join('')}
    </div>
  ` : '';

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      <!-- Header -->
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 3px solid ${pdf.navy}; padding-bottom: 20px;">
        <h1 style="color: ${pdf.navy}; margin: 0; font-size: 28px; font-weight: 700;">${data.assessmentName}</h1>
        <p style="color: ${pdf.mutedText}; margin: 10px 0 0 0; font-size: 16px;">${data.frameworkName}</p>
        <p style="color: ${pdf.mutedText}; margin: 5px 0 0 0; font-size: 14px;">Completed: ${data.completedDate}</p>
        ${data.vendorName ? `<p style="color: ${pdf.mutedText}; margin: 5px 0 0 0; font-size: 14px;">Vendor: ${data.vendorName}</p>` : ''}
        ${data.organizationName ? `<p style="color: ${pdf.mutedText}; margin: 5px 0 0 0; font-size: 14px;">Organization: ${data.organizationName}</p>` : ''}
      </div>
      
      <!-- Executive Summary -->
      <div style="text-align: center; margin-bottom: 40px; padding: 30px; background: linear-gradient(135deg, ${pdf.slate50} 0%, ${pdf.slate200} 100%); border-radius: 8px; border: 1px solid ${pdf.slate200};">
        <div style="font-size: 48px; font-weight: bold; color: ${pdfScoreColor(data.overallScore)}; margin-bottom: 10px;">${data.overallScore}%</div>
        <div style="font-size: 18px; color: ${pdf.gray700}; margin-bottom: 5px;">Overall Compliance Score</div>
        <div style="font-size: 14px; color: ${pdfScoreColor(data.overallScore)}; font-weight: 600;">${getScoreLabel(data.overallScore)}</div>
      </div>
      
      <!-- Section Scores -->
      <h2 style="color: ${pdf.teal}; margin-bottom: 20px; font-size: 22px; border-bottom: 2px solid ${pdf.teal}; padding-bottom: 10px;">Section Scores</h2>
      <div style="margin-bottom: 30px;">
        ${data.sectionScores.map(section => `
          <div style="margin-bottom: 15px; padding: 15px; background-color: ${pdf.gray50}; border-radius: 6px; border-left: 4px solid ${pdfScoreColor(section.percentage)};">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
              <span style="font-weight: 600; color: ${pdf.gray700}; font-size: 14px;">${section.title}</span>
              <div style="display: flex; align-items: center; gap: 10px;">
                <span style="font-weight: 600; color: ${pdfScoreColor(section.percentage)}; font-size: 14px;">${section.percentage}%</span>
                ${section.completed ? '<span style="color: ${pdf.riskLow}; font-size: 12px;">✓</span>' : ''}
              </div>
            </div>
            <div style="width: 100%; height: 8px; background-color: ${pdf.gray200}; border-radius: 4px; overflow: hidden;">
              <div style="width: ${section.percentage}%; height: 100%; background-color: ${pdfScoreColor(section.percentage)}; border-radius: 4px; transition: width 0.3s;"></div>
            </div>
          </div>
        `).join('')}
      </div>

      <!-- Key Findings -->
      <div style="margin-top: 40px; padding: 20px; background-color: ${pdf.blue50}; border-radius: 8px; border: 1px solid ${pdf.blue};">
        <h3 style="color: ${pdf.navy}; margin: 0 0 15px 0; font-size: 18px;">Key Findings</h3>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px;">
          <div>
            <strong style="color: ${pdf.gray700}; font-size: 14px;">Strengths:</strong>
            <ul style="margin: 8px 0 0 20px; padding: 0; color: ${pdf.neutralGray}; font-size: 13px; line-height: 1.6;">
              ${data.sectionScores.filter(s => s.percentage >= 70).map(s => `<li>${s.title} (${s.percentage}%)</li>`).join('')}
              ${data.sectionScores.filter(s => s.percentage >= 70).length === 0 ? '<li>No significant strengths identified</li>' : ''}
            </ul>
          </div>
          <div>
            <strong style="color: ${pdf.gray700}; font-size: 14px;">Areas for Improvement:</strong>
            <ul style="margin: 8px 0 0 20px; padding: 0; color: ${pdf.neutralGray}; font-size: 13px; line-height: 1.6;">
              ${data.sectionScores.filter(s => s.percentage < 60).map(s => `<li>${s.title} (${s.percentage}%)</li>`).join('')}
              ${data.sectionScores.filter(s => s.percentage < 60).length === 0 ? '<li>No critical areas identified</li>' : ''}
            </ul>
          </div>
        </div>
      </div>

      ${questionsHtml}
      ${wordDocumentsHtml}
      
      <!-- Assessment Summary -->
      <div style="margin-top: 40px; padding: 20px; background-color: ${pdf.blue50}; border-radius: 8px; border: 1px solid ${pdf.blue};">
        <h3 style="color: ${pdf.navy}; margin: 0 0 10px 0; font-size: 18px;">Assessment Summary</h3>
        <p style="color: ${pdf.gray700}; margin: 0; line-height: 1.6; font-size: 14px;">
          This comprehensive assessment evaluates your organization's supply chain risk management practices based on ${data.frameworkName} guidelines. 
          Scores above 80% indicate strong compliance, while scores below 60% suggest areas requiring immediate attention.
          ${data.questions && data.questions.length > 0 ? `This report includes detailed responses to ${data.questions.length} assessment questions.` : ''}
        </p>
      </div>
      
      <!-- Footer -->
      <div style="margin-top: 30px; text-align: center; color: ${pdf.neutralGray}; font-size: 12px; border-top: 1px solid ${pdf.gray200}; padding-top: 20px;">
        <p style="margin: 0;">Generated by VendorSoluce Supply Chain Risk Management Platform</p>
        <p style="margin: 5px 0 0 0;">© ${new Date().getFullYear()} VendorSoluce. All rights reserved.</p>
        ${data.assessmentId ? `<p style="margin: 5px 0 0 0; font-size: 11px;">Assessment ID: ${data.assessmentId}</p>` : ''}
      </div>
    </div>
  `;

  await generatePdfFromHtml(htmlContent, filename);
};
