/**
 * Autogenerated VIRA / weighted-intake artifacts for compliance evidence and audits.
 * Narrative text is English for consistency in exported records; UI remains i18n-driven.
 */

import { generatePdfFromHtml } from './generatePdf';
import { pdf } from './pdfHtmlPalette';
import {
  getRiskLevel,
  hasCompleteIntakeFactors,
  INTAKE_SLIDER_IDS,
  INTAKE_SLIDER_WEIGHTS,
  type IntakeSliderId,
} from './riskCalculations';

const FACTOR_LABELS_EN: Record<IntakeSliderId, string> = {
  data_access: 'Data access & sensitivity',
  criticality: 'Business criticality',
  security_controls: 'Security controls maturity',
  compliance: 'Compliance & regulatory exposure',
  system_exposure: 'System & integration exposure',
};

/** Ensure five factors for exports when portfolio data is partial. */
export function normalizeIntakeFactorsForExport(factors?: Record<string, number>): Record<string, number> {
  const out: Record<string, number> = {};
  for (const id of INTAKE_SLIDER_IDS) {
    const v = factors?.[id];
    out[id] = typeof v === 'number' && v >= 1 && v <= 5 ? Math.round(v) : 1;
  }
  return out;
}

export interface ViraIntakeExportInput {
  vendorName: string;
  /** 0–100 residual / portfolio risk score */
  riskScore: number;
  intakeFactors: Record<string, number>;
  generatedAtIso?: string;
  sector?: string;
  sourceNote?: string;
}

function formatFactorTable(factors: Record<string, number>): string {
  const lines: string[] = ['| Factor | Weight | Score (1–5) |', '|--------|--------|-------------|'];
  for (const id of INTAKE_SLIDER_IDS) {
    const w = INTAKE_SLIDER_WEIGHTS[id];
    const v = Math.min(5, Math.max(1, Math.round(Number(factors[id]) || 1)));
    lines.push(`| ${FACTOR_LABELS_EN[id]} | ${w} | ${v} |`);
  }
  return lines.join('\n');
}

/** Markdown record suitable for evidence packages, DPAs, or third-party reviews. */
export function buildVendorViraComplianceMarkdown(input: ViraIntakeExportInput): string {
  const when = input.generatedAtIso ?? new Date().toISOString();
  const level = getRiskLevel(input.riskScore);
  const intakeComplete = hasCompleteIntakeFactors(input.intakeFactors);
  const title = `VIRA weighted intake record — ${input.vendorName}`;

  return `# ${title}

**Generated:** ${when}  
**Vendor:** ${input.vendorName}  
${input.sector ? `**Sector / industry:** ${input.sector}  \n` : ''}**Intake status:** ${intakeComplete ? 'Complete (all five factors scored)' : 'Partial / incomplete — complete intake for full alignment'}  
**Residual risk score (0–100):** ${Math.round(input.riskScore)}  
**Tier:** ${level}

## Scope

This document is **machine-generated** from VendorSoluce VIRA™ weighted intake (same methodology as Vendor Risk Radar). It summarizes inherent-risk factors used for portfolio prioritization and **supports** third-party risk, procurement, and compliance workflows. It does not replace organizational policies, contractual terms, or regulator-specific submissions.

## Weighted intake factors (1 = stronger posture, 5 = higher exposure)

${formatFactorTable(input.intakeFactors)}

## Interpretation

- Scores are on a **0–100** scale (higher = more risk exposure), consistent with in-app Radar and reporting.
- Factors follow a **weighted** model (weights sum to 15); residual score reflects intake unless additional mitigation data is modeled elsewhere in the product.

${input.sourceNote ? `## Source\n\n${input.sourceNote}\n` : ''}

---

*VendorSoluce — Vendor Intelligence & Risk Assessment (VIRA™). Automated export; verify against live portfolio before external reliance.*
`;
}

export interface PortfolioRow {
  name: string;
  riskScore: number;
  intakeComplete: boolean;
  id?: string;
}

/** Portfolio-level index for SOC2 / audit folders: who has full VIRA intake. */
export function buildPortfolioViraComplianceIndexMarkdown(
  vendors: PortfolioRow[],
  generatedAtIso?: string
): string {
  const when = generatedAtIso ?? new Date().toISOString();
  const complete = vendors.filter((v) => v.intakeComplete).length;
  const lines = [
    `# VIRA portfolio compliance index`,
    ``,
    `**Generated:** ${when}`,
    `**Vendors listed:** ${vendors.length}`,
    `**Full VIRA intake complete:** ${complete}`,
    ``,
    `| Vendor | Residual risk (0–100) | VIRA intake |`,
    `|--------|------------------------|-------------|`,
  ];
  for (const v of vendors) {
    lines.push(
      `| ${v.name.replace(/\|/g, '/')} | ${Math.round(v.riskScore)} | ${v.intakeComplete ? 'Complete' : 'Incomplete'} |`
    );
  }
  lines.push(
    ``,
    `---`,
    `*Machine-generated index from VendorSoluce. Use with Vendor Risk Radar and VIRA reports for current state.*`
  );
  return lines.join('\n');
}

export function triggerTextDownload(filename: string, content: string, mime = 'text/markdown;charset=utf-8'): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Single-page PDF aligned with other platform PDFs (html2canvas path). */
export async function generateViraIntakePdf(input: ViraIntakeExportInput, filename: string): Promise<void> {
  const when = input.generatedAtIso ?? new Date().toISOString();
  const level = getRiskLevel(input.riskScore);
  const intakeComplete = hasCompleteIntakeFactors(input.intakeFactors);
  const rows = INTAKE_SLIDER_IDS.map((id) => {
    const v = Math.min(5, Math.max(1, Math.round(Number(input.intakeFactors[id]) || 1)));
    return `<tr><td style="padding:8px;border:1px solid ${pdf.slate200};">${escapeHtml(FACTOR_LABELS_EN[id])}</td><td style="padding:8px;border:1px solid ${pdf.slate200};text-align:center;">${INTAKE_SLIDER_WEIGHTS[id]}</td><td style="padding:8px;border:1px solid ${pdf.slate200};text-align:center;">${v}</td></tr>`;
  }).join('');

  const html = `
  <div style="font-family: Arial, sans-serif; max-width: 720px; margin: 0 auto; padding: 24px; color: ${pdf.gray700};">
    <div style="border-bottom: 2px solid ${pdf.navy}; padding-bottom: 16px; margin-bottom: 24px;">
      <h1 style="color: ${pdf.navy}; margin: 0; font-size: 22px;">VIRA™ weighted intake record</h1>
      <p style="margin: 8px 0 0 0; font-size: 13px; color: ${pdf.mutedText};">${escapeHtml(when)}</p>
    </div>
    <p style="font-size: 15px;"><strong>Vendor:</strong> ${escapeHtml(input.vendorName)}</p>
    ${input.sector ? `<p style="font-size: 14px;"><strong>Sector:</strong> ${escapeHtml(input.sector)}</p>` : ''}
    <p style="font-size: 14px;"><strong>Intake:</strong> ${intakeComplete ? 'Complete' : 'Partial / incomplete'}</p>
    <p style="font-size: 14px;"><strong>Residual risk (0–100):</strong> ${Math.round(input.riskScore)} &nbsp; <strong>Tier:</strong> ${escapeHtml(level)}</p>
    <h2 style="color: ${pdf.navy}; font-size: 16px; margin-top: 24px;">Weighted factors</h2>
    <table style="width:100%; border-collapse:collapse; font-size: 13px; margin-bottom: 24px;">
      <thead><tr style="background:${pdf.slate50};"><th style="padding:8px;border:1px solid ${pdf.slate200};text-align:left;">Factor</th><th style="padding:8px;border:1px solid ${pdf.slate200};">Weight</th><th style="padding:8px;border:1px solid ${pdf.slate200};">1–5</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <p style="font-size: 11px; color: ${pdf.neutralGray}; line-height: 1.5;">
      Machine-generated from VendorSoluce VIRA™ intake. Supports compliance and third-party risk workflows; does not replace legal or regulatory filings.
    </p>
  </div>`;

  await generatePdfFromHtml(html, filename);
}
